##
## EPITECH PROJECT, 2023
## test
## File description:
## f4
##

all: f4_equal_limit.out
f4_equal_limit.out: f4_equal_limit.o
	gcc -o f4_equal_limit.out f4_equal_limit.o

clean:
	rm -f *.o

fclean: clean
	rm -f *.out

re: fclean all
